Repository GSG-G11/InstaMart, pull requests merged in 2022-04, with the labels that each got.

#3 file structure
  .eslintrc.json
  .gitattributes
  .gitignore
  .vscode/settings.json
  client/.eslintrc.json
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/Components/index.js
  client/src/Pages/index.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  package-lock.json
  package.json
  server/__test__/products.test.ts
  server/src/app.ts
  server/src/controllers/index.ts
  server/src/controllers/middleware/index.ts
  server/src/controllers/orders/index.ts
  server/src/controllers/products/index.ts
  server/src/controllers/serveRootIndex.ts
  server/src/controllers/validation/index.ts
  server/src/database/config/index.ts
  server/src/database/models/index.ts
  server/src/index.ts
  server/src/routes/index.ts
  server/src/utilities/index.ts
  tsconfig.json
Labels: Awaiting Review

#8 remove nodemod and install ts-node-dev in order to support ts files
  package-lock.json
  package.json
Labels: Awaiting Review

#10 convert jwt sign , jwt verfiy to promise
  package-lock.json
  package.json
  server/__test__/products.test.ts
  server/src/utilities/index.ts
  server/src/utilities/jwtUtils.ts
Labels: Done

#14 create database
  .eslintrc.json
  server/src/database/config/connection.ts
  server/src/database/index.ts
  server/src/database/models/Category.ts
  server/src/database/models/Order.ts
  server/src/database/models/Product.ts
  server/src/database/models/Product_order.ts
  server/src/database/models/User.ts
  server/src/database/models/index.ts
  server/src/index.ts
Labels: Awaiting Review

#19 create route signup
  package-lock.json
  package.json
  server/src/controllers/index.ts
  server/src/controllers/users/index.ts
  server/src/controllers/users/signUp.ts
  server/src/controllers/validation/index.ts
  server/src/controllers/validation/signupValidation.ts
  server/src/database/config/connection.ts
  server/src/database/models/Category.ts
  server/src/database/models/Order.ts
  server/src/database/models/Product.ts
  server/src/database/models/Product_order.ts
  server/src/database/models/User.ts
  server/src/database/models/index.ts
  server/src/routes/index.ts
  server/src/utilities/jwtUtils.ts
Labels: Awaiting Review

#21 sign Up changes
  server/src/controllers/users/signUp.ts
  server/src/controllers/validation/index.ts
  server/src/utilities/jwtUtils.ts
Labels: Reviewer Approved

#23 create login controller
  package-lock.json
  server/src/controllers/index.ts
  server/src/controllers/users/login.ts
  server/src/controllers/users/signUp.ts
  server/src/controllers/validation/index.ts
  server/src/controllers/validation/logInSchema.ts
  server/src/database/models/User.ts
  server/src/routes/index.ts
  server/src/utilities/CustomizedError.ts
  server/src/utilities/bcryptjs/comparePassword.ts
  server/src/utilities/bcryptjs/hashPassword.ts
  server/src/utilities/index.ts
Labels: Awaiting Review

#26 create not found, server error, logout, auth/user routes
  client/src/example.jsx
  package-lock.json
  package.json
  server/src/controllers/index.ts
  server/src/controllers/middleware/index.ts
  server/src/controllers/middleware/isAuth.ts
  server/src/controllers/notFound.ts
  server/src/controllers/serverError.ts
  server/src/controllers/users/authUser.ts
  server/src/controllers/users/index.ts
  server/src/controllers/users/login.ts
  server/src/controllers/users/logout.ts
  server/src/controllers/users/signUp.ts
  server/src/database/index.ts
  server/src/database/models/Category.ts
  server/src/database/models/Order.ts
  server/src/database/models/Product.ts
  server/src/database/models/ProductOrder.ts
  server/src/database/models/Product_order.ts
  server/src/database/models/User.ts
  server/src/database/models/index.ts
  server/src/database/sync.ts
  server/src/index.ts
  server/src/routes/index.ts
  server/src/utilities/CustomizedError.ts
  server/src/utilities/jwtUtils.ts
Labels: Awaiting Review

#28 install husky and commitlint
  .commitlintrc.json
  .husky/commit-msg
  .husky/pre-commit
  package-lock.json
  package.json
Labels: Awaiting Review

#32 test: test notFound, logout, auth/user routes
  .github/workflows/node.js.yml
  jest.config.js
  package-lock.json
  package.json
  server/src/__test__/errors.test.ts
  server/src/__test__/users.test.ts
  server/src/controllers/middleware/isAuth.ts
  server/src/routes/index.ts
  server/src/utilities/CustomizedError.ts
  server/src/utilities/jwtUtils.ts
Labels: Awaiting Review

#33 test sign up route
  server/src/__test__/users.test.ts
  server/src/controllers/users/signUp.ts
Labels: Awaiting Review

#35 test:create test for login route
  package.json
  server/src/__test__/users.test.ts
  server/src/controllers/users/login.ts
  server/src/controllers/validation/logInSchema.ts
Labels: Awaiting Review

#22 protected routes
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/App.jsx
  client/src/Components/Home.jsx
  client/src/Components/Login.jsx
  client/src/Components/Profile.jsx
  client/src/Components/ProtectedRoute .jsx
  client/src/Components/index.js
  client/src/index.jsx
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/useAuth.jsx
  package-lock.json
  server/src/__test__/users.test.ts
  server/src/controllers/users/login.ts
  server/src/controllers/users/signUp.ts
Labels: Reviewer Approved

#37 add `/server/dist/` folder to `.gitignore`
  .gitignore
Labels: Awaiting Review, enhancement

#41 build: create products+categories db fakeData
  package.json
  server/src/controllers/index.ts
  server/src/controllers/products/addProduct.ts
  server/src/controllers/products/deleteProduct.ts
  server/src/controllers/products/editProduct.ts
  server/src/controllers/products/getProducts.ts
  server/src/controllers/products/index.ts
  server/src/controllers/validation/getProductsValidation.ts
  server/src/controllers/validation/index.ts
  server/src/database/fakeData/buildFakeData.ts
  server/src/database/fakeData/fakeData.ts
  server/src/database/models/Product.ts
  server/src/index.ts
  server/src/routes/index.ts
Labels: Reviewer Approved

#38 Signup component
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/Components/Login.jsx
  client/src/Components/ProtectedRoute.jsx
  client/src/Components/SignUp/SignUp.css
  client/src/Components/SignUp/index.jsx
  client/src/Hooks/useAuth.jsx
  client/src/images/SignUp.jpeg
  client/src/images/logo1.png
  client/src/index.jsx
Labels: Reviewer Approved

#48 feat: applying pagination to products route
  server/src/controllers/products/getProducts.ts
  server/src/controllers/validation/getProductsValidation.ts
  server/src/database/models/Product.ts
Labels: Reviewer Approved

#39 feat: create log in front page
  client/package-lock.json
  client/src/Components/Login.jsx
  client/src/Hooks/useAuth.jsx
  client/src/assets/logo.png
  client/src/example.jsx
  client/src/setupTests.js
  server/src/controllers/users/login.ts
Labels: Changes Requested

#49 42 header component
  client/package-lock.json
  client/public/index.html
  client/src/App.css
  client/src/App.jsx
  client/src/Components/header/Header.jsx
  client/src/Components/header/index.css
  client/src/Components/header/logo.png
Labels: Reviewer Approved

#51 feat: create get product by id route
  client/src/Components/header/Header.jsx
  client/src/Hooks/useAuth.jsx
  server/src/__test__/products.test.ts
  server/src/controllers/index.ts
  server/src/controllers/products/getProductByID.ts
  server/src/controllers/products/index.ts
  server/src/database/fakeData/fakeData.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#63 feat: create categories route
  package-lock.json
  server/src/controllers/products/getCategories.ts
  server/src/controllers/products/getProducts.ts
  server/src/controllers/products/index.ts
  server/src/controllers/validation/getProductsValidation.ts
  server/src/database/fakeData/fakeData.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#66 refactor: modify findAll query not to return createdAt, updatedAt fields to pass tests
  server/src/__test__/products.test.ts
  server/src/controllers/products/getCategories.ts
  server/src/database/fakeData/fakeData.ts
Labels: Awaiting Review

#68 build: isadmin middleware
  .github/workflows/node.js.yml
  server/src/__test__/products.test.ts
  server/src/controllers/middleware/index.ts
  server/src/controllers/middleware/isAdmin.ts
  server/src/routes/adminRouter/index.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#64 52 product details component
  client/src/App.jsx
  client/src/Components/ProductDetailsCard/index.jsx
  client/src/Components/ProductDetailsCard/style.css
  client/src/Components/header/Header.jsx
  client/src/Pages/ProductDetails/index.jsx
  client/src/Pages/ProductDetails/style.css
  client/src/Pages/index.js
Labels: Awaiting Review

#55 46 create cart component
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Components/Cart/CartProduct.jsx
  client/src/Components/Cart/TotalPrice.jsx
  client/src/Components/index.js
  client/src/Components/index.jsx
  client/src/Pages/Cart.jsx
  client/src/index.js
Labels: Awaiting Review

#70 refactor: update get-products controller to include category details
  client/src/App.jsx
  client/src/Components/header/Header.jsx
  server/src/__test__/products.test.ts
  server/src/controllers/products/getProducts.ts
Labels: Awaiting Review

#58 dashboard side component
  client/src/Components/Dashboard/DashboardAside.css
  client/src/Components/Dashboard/DashboardAside.jsx
  client/src/Components/Dashboard/index.js
Labels: Awaiting Review
